### ISSUE TITLE
Download the v2.0.0 tarball release fails to compile

### ISSUE THREAD

**Issue by golharam** [TimoLassmann/samstat#10]
It appears cmake does not clone the src/tld submodule used.  You need to clone this repo.  Then cmake will clone the submodule.

**Comment by TimoLassmann** [comment]
I was able to reproduce this error. Apparently the zip/tarballs automatically generated by github do not contain submodules:

> Currently zip/tarballs are generated using git-archive, which does not include submodules. If the git team adds that functionality to git-archive, we’ll be sure to update it so we can include submodules as well.

On my end everything works when cloning the repository:

```
git clone https://github.com/TimoLassmann/samstat.git
cd samstat
mkdir -p build
cd build
cmake ..
```
Could you verify if this works on you end? I will investigate how the issue can be resolved in the meantime.

**Comment by golharam** [comment]
Yes, everything works when I clone the repo.  Perhaps updating the readme to indicate this would be good. 

I ended up cloning the repo then checking out the v2.0.0 tag to get the matching version.

**Comment by TimoLassmann** [comment]
I am working on a work around - thanks for reporting!
