### ISSUE TITLE
install in non-standard location

### ISSUE THREAD

**Issue by splaisan** [TimoLassmann/samstat#14]
Hi

Since I want to deploy this on a shared server, I  need to install samstat away from the /usr/... standard location but since there is no ./configure (allowing me to set --prefix=/opt/biotools/samstat), I cannot set the DESTDIR to where I need it.
Is there a way to do this with the current install code?

Having samstat in bioconda would really be a plus for deployment in dockers and more.

thanks in advance

**Comment by splaisan** [comment]
OK,I think I found it:

replace ```cmake ..``` by ```cmake -DCMAKE_INSTALL_PREFIX=/opt/biotools/samstat ..``` then run ```make && make install```

creates a bin folder in /opt/biotools/samstat and puts the executable in it

cheers

**Comment by TimoLassmann** [comment]
Alternatively, you can also manually copy the samstat executable to /opt/biotools/samstat

**Comment by splaisan** [comment]
True but means I have installed with sudo which is not an option here. And risking to creates other files elsewhere in the process, var-lib, share etc.
Happy I could add the destdir argument, it all works now. thanks for the great tool

**Comment by TimoLassmann** [comment]
Makes sense - I'll add a section on non-standard install locations in the next release.
