### ISSUE TITLE
samstat not Running on Long File Names

### ISSUE THREAD

**Issue by imk1** [TimoLassmann/samstat#2]
I tried running samstat on a bam file, and it terminated immediately without producing any results.  The file had a very long name, so I re-named it to have a shorter name.  After re-naming the file, samstat started running.  Is samstat unable to handle very long file names?

Thanks.

**Comment by TimoLassmann** [comment]
Hi, long names _should_ not be a problem for samstat - I suspect something else is causing the problem. Could you send me a few of the lines causing the problem?

**Comment by imk1** [comment]
Running the following command did not work:
samstat /pylon5/mc5fq4p/ikaplow/AnimalAtac/BrainRep2SubsampleMulti2/cromwell-executions/atac/d27cd995-cca7-4c06-b7ac-e3df10850d11/call-filter/shard-0/execution/Animal1_Brain_2_PFE116A15_S14_R1_001.merged_sample60M.nodup.bam

Running the following command did work:
samstat /pylon5/mc5fq4p/ikaplow/AnimalAtac/BrainRep2SubsampleMulti2/cromwell-executions/atac/d27cd995-cca7-4c06-b7ac-e3df10850d11/call-filter/shard-0/execution/test.bam

test.bam was created by running:
cp /pylon5/mc5fq4p/ikaplow/AnimalAtac/BrainRep2SubsampleMulti2/cromwell-executions/atac/d27cd995-cca7-4c06-b7ac-e3df10850d11/call-filter/shard-0/execution/Animal1_Brain_2_PFE116A15_S14_R1_001.merged_sample60M.nodup.bam /pylon5/mc5fq4p/ikaplow/AnimalAtac/BrainRep2SubsampleMulti2/cromwell-executions/atac/d27cd995-cca7-4c06-b7ac-e3df10850d11/call-filter/shard-0/execution/test.bam

**Comment by TimoLassmann** [comment]
Hi - I meant some of the bam / sam lines so I can run these locally and diagnose the problem.

**Comment by imk1** [comment]
The two bam files (the one that worked and the one that did not work) were identical; the only difference was the file names.
