### ISSUE TITLE
samstat output is different than bowtie2 stats

### ISSUE THREAD

**Issue by bounlu** [TimoLassmann/samstat#3]
The output stats from bowtie2 and samstat on the same bam file are different:

**bowtie2:**
```
18657869 reads; of these:
  18657869 (100.00%) were unpaired; of these:
    1995321 (10.69%) aligned 0 times
    12773937 (68.46%) aligned exactly 1 time
    3888611 (20.84%) aligned >1 times
89.31% overall alignment rate
```

**samstat:**

<img width="768" alt="samstat" src="https://user-images.githubusercontent.com/17899927/71098299-6fce2200-21ec-11ea-9d14-5a083e3751f6.png">

any explanation?

**Comment by TimoLassmann** [comment]
Samstat works only on SAM/BAM lines that represent primary alignments and excludes all reads that fail platform/vendor quality checks. I suspect that this is where the discrepancies come from.

**Comment by bounlu** [comment]
I see, you are using the flag -F 768. Thanks for the info.
