### ISSUE TITLE
./autogen.sh not found

### ISSUE THREAD

**Issue by JoelTV2021** [TimoLassmann/samstat#5]
Hi! 
I have a problem with Samstat's installation, when I put :
$./autogen.sh
terminal said that:
joel@joel-desktop:~/samstat$ ./autogen.sh 
Submodule 'tldevel' (https://github.com/TimoLassmann/tldevel.git) registered for path 'tldevel'
Cloning into '/home/joel/samstat/tldevel'...
Submodule path 'tldevel': checked out '7541a28641752c9eb89d7926928af22471595c45'
./autogen.sh: 12: autoreconf: not found
and then I try to run make, 
make: *** No targets specified and no makefile found.  Stop.

I want to install this software is very necessary for my research.

Thanks.
Joel

**Comment by adamalexander-gh** [comment]
I'm still struggling to install this so YMMV; but to get past this message I found I needed to install autoconf. On fedora I used: 
`sudo dnf install autoconf `
