### ISSUE TITLE
Samstat segfaults on some inputs

### ISSUE THREAD

**Issue by JacobPorter** [TimoLassmann/samstat#7]
Hi,
I am a developer with https://www.bv-brc.org/, and we use samstat. We had some BAM files that produce segfaults with samstat version 1.5.1. I wonder if you could look into it and fix the problem. The reads come from RNA-Seq jobs with 454 sequences aligned against genome 234826.6 (https://www.bv-brc.org/view/Genome/234826.6) with bowtie2. We used SRA numbers SRR528324 and SRR528310.

Two BAM file test cases can be found here: https://zenodo.org/record/6609171

Thanks,
Jacob S. Porter, PhD

**Comment by TimoLassmann** [comment]
Hi, I have not updated samstat in a while (and should!). Thanks for providing the bam's I will have a look.

**Comment by TimoLassmann** [comment]
Hi Jacob,
I updated samstat to version 2.0. Hope this fixed the issues you've been having. 
Thanks, Timo
