### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by selmanurk** [TimoLassmann/samstat#8]
hello, when I try to build samstat the cmake does not work. what can I do ?

**Comment by TimoLassmann** [comment]
Could you send me the error messages? Thx, T

**Comment by selmanurk** [comment]
Hi,

ı am using a slurm server, at first I was getting the error as
cmake version 2.8 at least 3.2 required

alıngan with the messsage I shared below, although cmake-3.2 is built as I can see with the command module align. 

After I batched the cmake.. command as /centos/cmake-3.2 .. as a job // sbatch txt.

That part seem to worked but I kept getting this part 
![4B7FC630-063A-47E2-BF5A-90A09C51C27B](https://user-images.githubusercontent.com/108890766/177894894-7b3ff9d8-89af-45e3-abf1-017843261552.png)


Thank you so much,
S

**Comment by selmanurk** [comment]
Along*

**Comment by TimoLassmann** [comment]
Hmm. Can you send me the slurm script so I can tell what is actually being attempted? Thx, T

**Comment by selmanurk** [comment]
![779FC4D1-1A76-4FFB-9D09-C4B4F51E5398](https://user-images.githubusercontent.com/108890766/177895410-67715a4f-2e5e-48b8-a8ae-84fc1bfda1f7.jpeg)

I just downloaded samstat via git clone and trying to install,
Thank you

**Comment by TimoLassmann** [comment]
Hmm - I *think* line 10 contains and error: you need "&&" between the cd and cmake command or put the commands on two lines like this: 
```
cd <blah>/samstat/build 
cmake ..
make 
make install  
```
Hope this helps, T

**Comment by selmanurk** [comment]
Hi again,
Sorry for getting back later, its because of the time difference. In the slurm script I think cmake worked. Would you mind telling what are the arguments or “targets” for last 2 lines 
“Make 
Make install”

because this is the final error I am
Getting 
![F1A0D642-D840-495A-B5F2-2E2FEAD5B6EC](https://user-images.githubusercontent.com/108890766/177972148-4e9979c2-4b2d-4ec6-aba0-826f84a07241.jpeg)

thank you a lot,
Selma

**Comment by selmanurk** [comment]
Wrong picture, this is

![D752424A-A48F-4713-BEB3-1E8287F24726](https://user-images.githubusercontent.com/108890766/177972489-ee43f7a2-5343-48f3-9c0b-61ff0ca72384.png)
