### ISSUE TITLE
one more try -- make make install 

### ISSUE THREAD

**Issue by selmanurk** [TimoLassmann/samstat#9]
Hi again, I hope I am not disturbing you. I left a comment on your answer to my other the other day, but now I see you have closed it so maybe you didn't see it. Like I said, when I was able to make cmake command work after sbatching it, would you mind tell me what are the arguments or "targets" for the last to
 make
make install
 
commands for installing? I am going to attach the error I get below, thank you,
Selma

make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.

**Comment by TimoLassmann** [comment]
Hi, I believe there is an error in your slurm script as indicated before. Please try with these lines: 
```
cd <blah>/samstat/build 
cmake ..
make 
make install  
```

Thanks, T

**Comment by selmanurk** [comment]
No that's not the problem, but thank you. 
Selma

**Comment by TimoLassmann** [comment]
This works for me on multiple machines:
`cd build && cmake .. && make && sudo make install`

**Comment by selmanurk** [comment]
Thank you. Best, Selma
